baseURL: "https://gvt.xorb.ooo/"

module:
  hugoVersion:
    min: "0.146.0"
locale: "en-us"
title: "GVT"
theme: "PaperMod"
buildFuture: true
enableRobotsTXT: true

# search page needs the JSON index
outputs:
  home: ["HTML", "RSS", "JSON"]

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema
  images: ["/gvt-card.png"]
  fuseOpts:
    keys: ["title", "permalink", "summary", "content", "description", "speaker"]
    threshold: 0.3
    ignoreLocation: true
  title: "Games and Visuals Trójmiasto"
  description: "GVT Meetups"
  defaultTheme: auto # dark, light, auto
  homeInfoParams:
    Title: "Games and Visuals Trójmiasto"
    Content: "Monthly gamedev meetups in Trójmiasto, join us!"
  socialIcons:
    - name: discord
      url: "/discord"
    - name: youtube
      title: "Old playlist"
      url: "https://www.youtube.com/playlist?list=PL97f0is2Y4VnWVgBYOlmYNJIRINzCwPvz"
    - name: youtube
      title: "New channel"
      url: "https://www.youtube.com/@gv3-yt"
    - name: linkedin
      url: "https://www.linkedin.com/company/games-visuals-tricity"
    - name: facebook
      url: "https://www.facebook.com/games.visuals"

  cover:
    hiddenInSingle: true
  footer:
    text: "Powered by [ururus](https://xorb.ooo)"

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
