[phases.setup]
cmds = [
    "sudo apt-get update && sudo apt-get install -y --no-install-recommends curl wget",
    "wget https://github.com/gohugoio/hugo/releases/download/v0.127.0/hugo_extended_0.127.0_Linux-64bit.tar.gz -O hugo.tar.gz",
    "tar -xvzf hugo.tar.gz -C /usr/local/bin",
    "ls -la /usr/local/bin"
]

[ phases.build ]
cmds = [
    "hugo version",
    "hugo --minify"
]

[ environment ]
HUGO_VERSION = "0.127.0"

[[ nixpacks.included_files ]]
paths = ["/public"]